- name: Git personal setup email
  git_config:
      name: user.email
      scope: global
      value: "alexiszamanidis@outlook.com"
  tags:
      - git-personal

- name: Git personal setup name
  git_config:
      name: user.name
      scope: global
      value: "alexiszamanidis"
  tags:
      - git-personal

##########################################################

- name: Git work setup email
  git_config:
      name: user.email
      scope: global
      value: "Alexis.Zamanidis@Openbet.com"
  tags:
      - git-work

- name: Git work setup name
  git_config:
      name: user.name
      scope: global
      value: "alexis.zamanidis"
  tags:
      - git-work
